# Generated by Django 6.1 on 2026-08-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True, help_text="Free-text summary of the day's activities.")),
                ('meals', models.CharField(blank=True, help_text='e.g. "Breakfast, Lunch, Dinner"', max_length=255)),
                ('accommodation', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='packages.tourpackage')),
            ],
            options={
                'db_table': 'itineraries',
                'ordering': ['package', 'day_number'],
                'constraints': [models.UniqueConstraint(fields=('package', 'day_number'), name='unique_day_number_per_package')],
            },
        ),
    ]
