# Generated by Django 6.1 on 2026-08-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['package', 'day_number'], 'verbose_name': 'Itinerary', 'verbose_name_plural': 'Itineraries'},
        ),
    ]
