# Generated by Django 6.1 on 2026-08-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_alter_itinerary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='transportation',
            field=models.CharField(blank=True, help_text='e.g. Flight, Private vehicle, Train', max_length=255),
        ),
    ]
