# Generated by Django 6.1 on 2026-08-31 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_coupon_code_booking_discount_amount_and_more'),
        ('packages', '0004_cancellationpolicy_cancellationrule_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='package_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.packageservice'),
        ),
    ]
