# Generated by Django 6.1 on 2026-09-04 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingservice_package_service'),
        ('packages', '0006_pickuppoint_tourpackage_pickup_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='packages.pickuppoint'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_point_name',
            field=models.CharField(blank=True, help_text='Snapshot of pickup point city/name at booking time', max_length=255),
        ),
    ]
