# Generated by Django 6.1 on 2026-08-08 12:14

import django.core.validators
import django.db.models.deletion
import packages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_travelers', models.PositiveIntegerField()),
                ('available_slots', models.PositiveIntegerField()),
                ('package_type', models.CharField(choices=[('adventure', 'Adventure'), ('honeymoon', 'Honeymoon'), ('family', 'Family'), ('pilgrimage', 'Pilgrimage'), ('wildlife', 'Wildlife'), ('beach', 'Beach'), ('cultural', 'Cultural'), ('luxury', 'Luxury')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], default='easy', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=packages.models.package_featured_image_path)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_packages', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='destinations.destination')),
            ],
            options={
                'db_table': 'tour_packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='packages.tourpackage')),
            ],
            options={
                'db_table': 'package_inclusions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=packages.models.package_gallery_image_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.tourpackage')),
            ],
            options={
                'db_table': 'package_images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='packages.tourpackage')),
            ],
            options={
                'db_table': 'package_faqs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PackageExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='packages.tourpackage')),
            ],
            options={
                'db_table': 'package_exclusions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PackageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('day_number', models.PositiveIntegerField()),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='packages.tourpackage')),
            ],
            options={
                'db_table': 'package_activities',
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['status'], name='tour_packag_status_a993ca_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['package_type'], name='tour_packag_package_626eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['is_featured'], name='tour_packag_is_feat_6cb266_idx'),
        ),
    ]
