# Generated by Django 6.1 on 2026-08-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageactivity',
            options={'ordering': ['day_number', 'id'], 'verbose_name': 'Package Activity', 'verbose_name_plural': 'Package Activities'},
        ),
    ]
