# Generated by Django 6.1 on 2026-08-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packageactivity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageimage',
            name='place_name',
            field=models.CharField(blank=True, help_text="Name of the place shown in this photo, e.g. 'Nubra Valley'.", max_length=255),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='pickup_location',
            field=models.CharField(blank=True, help_text="Where travelers will be picked up from, e.g. 'Leh Airport' or 'Hotel lobby, Panaji'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Short description of the place/photo.', max_length=255),
        ),
    ]
