# Generated by Django 6.1 on 2026-08-31 19:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('packages', '0003_packageimage_place_name_tourpackage_pickup_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Cancellation Policy', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cancellation_policies',
            },
        ),
        migrations.CreateModel(
            name='CancellationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_min', models.PositiveIntegerField(help_text='Minimum days before travel for this rule')),
                ('days_before_max', models.PositiveIntegerField(blank=True, help_text='Max days (null = no upper limit)', null=True)),
                ('refund_percent', models.PositiveIntegerField(help_text='0-100', validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cancellation_rules',
                'ordering': ['-days_before_min'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage')], default='fixed', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percent discounts', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_trip_type', models.CharField(blank=True, choices=[('group_tour', 'Group Tour'), ('independent_package', 'Independent Package')], help_text='Blank = applies to all', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_included', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True, help_text='If required and service unavailable, booking blocked')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'package_services',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageTravelDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('available_slots', models.PositiveIntegerField(blank=True, help_text='Overrides package available_slots for this date if set', null=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'package_travel_dates',
                'ordering': ['travel_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('transportation', 'Transportation'), ('accommodation', 'Accommodation'), ('guide', 'Guide'), ('activity', 'Activity'), ('sightseeing', 'Sightseeing'), ('meals', 'Meals'), ('other', 'Other')], db_index=True, max_length=30)),
                ('service_category', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('private_vehicle', 'Private Vehicle'), ('airport_transfer', 'Airport Transfer'), ('hotel', 'Hotel'), ('room_type', 'Room Type'), ('guide_service', 'Guide Service'), ('activity_service', 'Activity Service'), ('attraction', 'Attraction'), ('meal_service', 'Meal Service'), ('other', 'Other')], default='other', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='per_person', help_text='e.g. per_person, per_night, per_trip', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Optional capacity per day', null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'travel_services',
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='best_time_to_visit',
            field=models.CharField(blank=True, help_text="e.g. 'October to March'", max_length=255),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='category',
            field=models.CharField(blank=True, help_text='Optional category for independent packages', max_length=100),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Company service fee added on top of service costs for independent packages.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='trip_type',
            field=models.CharField(choices=[('group_tour', 'Group Tour'), ('independent_package', 'Independent Package')], db_index=True, default='group_tour', max_length=30),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['trip_type'], name='tour_packag_trip_ty_5b7ea5_idx'),
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='package',
            field=models.OneToOneField(blank=True, help_text='Null = global default policy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policy', to='packages.tourpackage'),
        ),
        migrations.AddField(
            model_name='cancellationrule',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='packages.cancellationpolicy'),
        ),
        migrations.AddField(
            model_name='packageservice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_services', to='packages.tourpackage'),
        ),
        migrations.AddField(
            model_name='packagetraveldate',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_dates', to='packages.tourpackage'),
        ),
        migrations.AddIndex(
            model_name='travelservice',
            index=models.Index(fields=['service_type'], name='travel_serv_service_2bc3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='travelservice',
            index=models.Index(fields=['service_category'], name='travel_serv_service_d9f3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='travelservice',
            index=models.Index(fields=['is_active'], name='travel_serv_is_acti_802be9_idx'),
        ),
        migrations.AddField(
            model_name='packageservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_usages', to='packages.travelservice'),
        ),
        migrations.AddConstraint(
            model_name='packagetraveldate',
            constraint=models.UniqueConstraint(fields=('package', 'travel_date'), name='unique_package_travel_date'),
        ),
        migrations.AddIndex(
            model_name='packageservice',
            index=models.Index(fields=['package'], name='package_ser_package_e10a23_idx'),
        ),
    ]
