# Generated by Django 6.1 on 2026-08-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_cancellationpolicy_cancellationrule_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageservice',
            name='is_default_selected',
            field=models.BooleanField(default=False, help_text='If selectable, whether this is pre-selected'),
        ),
        migrations.AddField(
            model_name='packageservice',
            name='is_user_selectable',
            field=models.BooleanField(default=False, help_text='If true, user can choose this option among its group'),
        ),
        migrations.AddField(
            model_name='packageservice',
            name='option_group',
            field=models.CharField(blank=True, db_index=True, help_text="E.g. 'transport' or 'hotel' - mutually exclusive; only one per group is charged", max_length=50),
        ),
    ]
