# Generated by Django 6.1 on 2026-09-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_packageservice_is_default_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, help_text='Big city name e.g. Mumbai, Delhi, Pune', max_length=100)),
                ('name', models.CharField(help_text="Specific pickup location e.g. 'Dadar Station', 'Leh Airport'", max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for distance calculation', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for distance calculation', max_digits=9, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pickup_points',
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city'], name='pickup_poin_city_513f0e_idx'), models.Index(fields=['is_active'], name='pickup_poin_is_acti_50e536_idx')],
                'constraints': [models.UniqueConstraint(fields=('city', 'name'), name='unique_pickup_city_name')],
            },
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='pickup_points',
            field=models.ManyToManyField(blank=True, help_text='For group tours: pickup hubs where we bring travelers with us.', related_name='packages', to='packages.pickuppoint'),
        ),
    ]
