# Generated by Django 6.1 on 2026-09-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_pickuppoint_tourpackage_pickup_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='flexibility_note',
            field=models.CharField(blank=True, help_text="Short flexibility note for independent — e.g., 'Choose your own travel dates & hotel tier'.", max_length=500),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='independent_highlights',
            field=models.TextField(blank=True, help_text="Highlights for independent packages — e.g., 'Private vehicle, flexible dates, 24/7 support'. Shown only on independent detail pages."),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='travel_requirements',
            field=models.TextField(blank=True, help_text='Travel requirements for independent packages — e.g., passport, visa, health. Leave blank to hide.'),
        ),
    ]
