# Generated by Django 6.1 on 2026-08-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(help_text="Admin's UPI ID that receives payments, e.g. 'travelbooking@okhdfcbank'.", max_length=100)),
                ('merchant_name', models.CharField(default='Travel Booking System', help_text='Name shown to the customer in their UPI app.', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
                'db_table': 'payment_settings',
            },
        ),
    ]
