# Generated by Django 6.1 on 2026-08-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='UPI transaction reference/UTR number the customer provides after paying. Used by an admin to manually verify the payment actually arrived before marking it paid — customers cannot mark their own UPI payment as paid.', max_length=100),
        ),
    ]
