# Generated by Django 6.1 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='qr_image',
            field=models.ImageField(blank=True, help_text='Optional QR code image for this UPI ID. Shown to customers at checkout alongside the UPI deep link.', null=True, upload_to='payments/qr/'),
        ),
    ]
