# Generated by Django 6.1 on 2026-08-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentsettings_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('mock', 'Mock')], default='razorpay', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Legacy UPI reference. For Razorpay this stores razorpay_payment_id after verify.', max_length=100),
        ),
    ]
