# Generated by Django 6.1 on 2026-09-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, this destination will appear on the homepage featured section. Otherwise it only appears on the All Destinations page.'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_featured'], name='destination_is_feat_7a4e6a_idx'),
        ),
    ]
